### ISSUE TITLE
where can we find the express api for this app

### ISSUE THREAD

**Issue by outranker** [VertikaJain/react-chat-app#1]
I was going to run this react app locally but api is also needed, apparently
I couldn't find the express backend for this app from your repos.
Could you please provide one if possible?

**Comment by VertikaJain** [comment]
Hi,

I have provided the URL of the backend repository in the readme.md file ->
Resources -> 3. Backend - NodeJS

I'm providing the same link here for backend -
https://github.com/VertikaJain/node-express-ts-chat-app



Happy Coding!
Vertika Jain

**Comment by outranker** [comment]
Thank you very much!
I will try it

By the way, can libsignal-protocol-javascript be used with React Native? I am not sure if you know this but i thought it wouldn't hurt to ask

**Comment by VertikaJain** [comment]
Well, I haven't worked with React Native yet. But we can collaborate and give it a shot sometime.

**Comment by outranker** [comment]
Thank you very much~
I hope we will sometime!
